# Site settings
author: Lindsey Wells
title: Linz Can Code
header-img: img/home-bg.png
email: lindsey.wells84@gmail.com
copyright_name: Lindsey Wells
description: > # this means to ignore newlines until "baseurl:"
  My journey from Camera Operator to Coder
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Linziw

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
